In [21]:
import pandas as pd
import numpy as np
import plotly.express as px
import statsmodels.api as sm

In [22]:
sleep_data = pd.read_csv('dataset_2191_sleep.csv')
sleep_data.head()

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9

In [23]:
sleep_data.describe()

,body_weight,brain_weight,predation_index,sleep_exposure_index,danger_index
count,62.000000,62.000000,62.000000,62.000000,62.000000
mean,198.789984,283.134194,2.870968,2.419355,2.612903
std,899.158011,930.278942,1.476414,1.604792,1.441252
min,0.005000,0.140000,1.000000,1.000000,1.000000
25%,0.600000,4.250000,2.000000,1.000000,1.000000
50%,3.342500,17.250000,3.000000,2.000000,2.000000
75%,48.202500,166.000000,4.000000,4.000000,4.000000
max,6654.000000,5712.000000,5.000000,5.000000,5.000000

In [24]:
columns = sleep_data.columns
for column in columns:
    sleep_data[column] = pd.to_numeric(sleep_data[column], errors='coerce')

In [25]:
sleep_data = sleep_data.sort_values(by='max_life_span', ascending=True)

px.scatter(sleep_data, x='max_life_span', y='total_sleep', trendline='ols')

In [26]:
columns =columns.drop('total_sleep')
for column in columns:
    fig = px.scatter(
        sleep_data,
        x=column,
        y='total_sleep',
        trendline='ols',
        title=f'Total Sleep vs {column}'
    )
    fig.show()

In [27]:
model1 = sm.OLS.from_formula('total_sleep ~ body_weight + brain_weight + predation_index + sleep_exposure_index + danger_index', data=sleep_data)

In [29]:
model1_results = model1.fit()
print(model1_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            total_sleep   R-squared:                       0.546
Model:                            OLS   Adj. R-squared:                  0.502
Method:                 Least Squares   F-statistic:                     12.49
Date:                Wed, 01 Oct 2025   Prob (F-statistic):           5.60e-08
Time:                        17:14:12   Log-Likelihood:                -147.52
No. Observations:                  58   AIC:                             307.0
Df Residuals:                      52   BIC:                             319.4
Df Model:                           5
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               14.7853      0.959     15.415      0.000      12.861      16.710
body_weight           7.804e-05      0.001      0.058      0.954      -0.003       0.003
brain_weight            -0.0008      0.001     -0.570      0.571      -0.003       0.002
predation_index          2.6494      0.902      2.938      0.005       0.840       4.459
sleep_exposure_index    -0.5026      0.508     -0.990      0.327      -1.522       0.517
danger_index            -4.0611      1.147     -3.540      0.001      -6.363      -1.759
==============================================================================
Omnibus:                        0.741   Durbin-Watson:                   1.899
Prob(Omnibus):                  0.690   Jarque-Bera (JB):                0.848
Skew:                           0.189   Prob(JB):                        0.655
Kurtosis:                       2.544   Cond. No.                     4.66e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.66e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Analysis of Model

From this model we can see issues with multicolinearity and other influencing variables. We can also see high p-values for some of the variables. While the model does account for 54% of the variance in total sleep, it does not account for all of it, making it only partially useful.

## Future Work
I plan to eliminate and modify some variables to try and improve the model.